<a href="https://colab.research.google.com/github/Daffa-afaf/Data-Mining/blob/main/Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [13]:
dataset = pd.read_csv('Datacoba.csv')
x = dataset.iloc[:, :-1].values # ambil semua record kecuali terakhir
y = dataset.iloc[:, -1].values # ambil kolom/record yang terakhir

In [14]:
print (x)

[['Budi' 1001 21.0 3.5]
 ['Susanti' 1002 22.0 3.1]
 ['Loren' 1003 20.0 3.8]
 ['Jarwo' 1004 nan 3.1]
 ['Adit' 1005 21.0 3.6]
 ['Upin' 1006 20.0 3.3]
 ['Ipin' 1007 20.0 nan]
 ['Ultraman' 1008 21.0 3.7]
 ['Gatot' 1009 21.0 3.0]
 ['Malik' 1010 20.0 3.4]]


In [15]:
print (y)

['Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'Yes' 'No' 'No']


In [16]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:4])
x[:, 1:4] = imputer.transform(x[:, 1:4])

In [17]:
print (x)

[['Budi' 1001.0 21.0 3.5]
 ['Susanti' 1002.0 22.0 3.1]
 ['Loren' 1003.0 20.0 3.8]
 ['Jarwo' 1004.0 20.666666666666668 3.1]
 ['Adit' 1005.0 21.0 3.6]
 ['Upin' 1006.0 20.0 3.3]
 ['Ipin' 1007.0 20.0 3.388888888888889]
 ['Ultraman' 1008.0 21.0 3.7]
 ['Gatot' 1009.0 21.0 3.0]
 ['Malik' 1010.0 20.0 3.4]]


In [18]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [19]:
print (x)

[[0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1001.0 21.0 3.5]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1002.0 22.0 3.1]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1003.0 20.0 3.8]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1004.0 20.666666666666668 3.1]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1005.0 21.0 3.6]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 1006.0 20.0 3.3]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 1007.0 20.0 3.388888888888889]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 1008.0 21.0 3.7]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1009.0 21.0 3.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1010.0 20.0 3.4]]


In [20]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [21]:
print (y)

[1 0 1 0 1 0 0 1 0 0]


In [25]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=1)

In [26]:
print (x_train)

[[0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 1007.0 20.0 3.388888888888889]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1005.0 21.0 3.6]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1001.0 21.0 3.5]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 1004.0 20.666666666666668 3.1]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 1002.0 22.0 3.1]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 1008.0 21.0 3.7]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1009.0 21.0 3.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 1006.0 20.0 3.3]]


In [27]:
print (x_test)

[[0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1003.0 20.0 3.8]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1010.0 20.0 3.4]]


In [28]:
print (y_train)

[0 1 1 0 0 1 0 0]


In [29]:
print (y_test)

[1 0]


In [31]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [32]:
print (x_train)

[[0.0 0.0 0.0 2.6457513110645903 -0.3779644730092272 0.0 0.0
  -0.3779644730092272 -0.3779644730092272 -0.3779644730092272
  0.6644105970267493 -1.386750490563077 0.22070653588675807]
 [1.0 0.0 0.0 -0.3779644730092272 -0.3779644730092272 0.0 0.0
  -0.3779644730092272 -0.3779644730092272 -0.3779644730092272
  -0.0949157995752499 0.2773500981126107 1.103532679433794]
 [0.0 1.0 0.0 -0.3779644730092272 -0.3779644730092272 0.0 0.0
  -0.3779644730092272 -0.3779644730092272 -0.3779644730092272
  -1.6135685927792485 0.2773500981126107 0.6853518745957242]
 [0.0 0.0 0.0 -0.3779644730092272 2.6457513110645903 0.0 0.0
  -0.3779644730092272 -0.3779644730092272 -0.3779644730092272
  -0.4745789978762495 -0.27735009811261657 -0.9873713447565529]
 [0.0 0.0 0.0 -0.3779644730092272 -0.3779644730092272 0.0 0.0
  2.6457513110645903 -0.3779644730092272 -0.3779644730092272
  -1.2339053944782488 1.9414506867882984 -0.9873713447565529]
 [0.0 0.0 0.0 -0.3779644730092272 -0.3779644730092272 0.0 0.0
  -0.37796447

In [33]:
print (x_test)

[[0.0 0.0 0.0 -0.3779644730092272 -0.3779644730092272 1.0 0.0
  -0.3779644730092272 -0.3779644730092272 -0.3779644730092272
  -0.8542421961772492 -1.386750490563077 1.9398942891099316]
 [0.0 0.0 0.0 -0.3779644730092272 -0.3779644730092272 0.0 1.0
  -0.3779644730092272 -0.3779644730092272 -0.3779644730092272
  1.8034001919297482 -1.386750490563077 0.2671710697576545]]
